---
title: "Applied Statistics"
---

This course consists of three, three-hour sessions which aim to cover some of the key idea of statistics and how these can be used in practice to design experiments, collect data, build and analyse suitable statistical models and interpret results.  The course may be taken by any postgraduate research student but is aimed mainly at those students in year 1. Students are expected to undertake all 3 sessions in a block. 

The course is delivered by Professor Adrian Bowman (adrian.bowman@glasgow.ac.uk), School of Mathematics and Statistics, University of Glasgow.  Delivery will be entirely on-line.  Each session will involve a mix of on-line lecture material, exercises and practical work, and an open forum for discussion and questions.  The Zoom links for each session will be sent out by e-mail to those students who have registered for the course.  Participants should join the course through these links at the start of each session.

From discussion during previous runs of this course, it is clear that most participants are keen to learn about the statistical computing system R.  Some gentle R will therefore be included in the course, but this is entirely optional.  There will be only a small amount of this kind of material in the first session, but we will discuss the potential benefits of R and the extent to which you would like to use it in later sessions.  In order to take advantage of this, including in the first session, please:

* install R for your operating system from the links available at https://cloud.r-project.org; this should be a straightforward process;
* install the R Studio ‘front-end’ from https://rstudio.com/products/rstudio/download/#download; this should also be straightforward.

### Session 1: Basic ideas about data and experiments

The issues involved in designing a good experiment will be discussed, with a wide variety of examples used for illustration.  The general issue of 'Where do data come from?' will be discussed in terms of populations and samples.  Elementary concepts of statistical analysis such as standard error, confidence intervals, hypothesis tests and power will be explored.  There will be a strong emphasis on graphical presentation, both for data and for concepts.  Pointers will be given to good design strategies for particular settings.  A number of case studies will be explored.

### Session 2: Building and using linear models

Simple ideas of linear regression will be described and these will be developed into more complex models involving multiple explanatory variables and factors.  The emphasis will be on strategies for building and checking a model, and on interpreting the results of the analysis.  For those who wish to gain some experience of the widely used statistical computing environment R, a brief introduction will be provided and scripts for the modelling analysis will be made available.

### Session 3: A wider variety of models

This session will cover models for some other types of data which commonly arise in experiments, including counts and proportions and repeated measurements or random effects.  Some pointers to wider issues will also be given, including more flexible regression models.
